# Data Types 

"It's all just 0s and 1s!" You might have heard that before. For the most part TODO quantum computing, it's true. Computers have binary digits (bits), and that's how they store more complicated pieces of data and instructions.

Fortunately, we will not ever have to think about how the computer handles those low level details. We must, however, be concerned with the different *types* of data our `R` and `Python` programs can use in programs.

There will be similarities between `Python`'s types and `R`s types. However, `Python` wasn't expressly created for data analysis, so many of the `Python` types that are similar to `R` types will be defined in third party libraries/modules.

If you're ever unsure what type a variable has, use `type()` (in `Python`) or `typeof()` (in `R`) to query it.

TODO Test [@R-bookdown]


## Integers, Strings and Floating Point Numbers

In `Python`, the simplest types are `str` (short for string), `int` (short for integer), and `float` (short for floating point). 

```{python}
# in python
print(type('a'))
print(type(1))
print(type(1.3))
```

We will write much more complicated programs, so we will need to save different values as *variables*. We create them by using the assignment operator `=`. The name of the variable goes on the left of the assignment operator.

```{Python}
# in python
my_name = 'Charlie'
print('Hello! My name is ', my_name, '.', sep = '')
```

In `R`, there are no scalar types like this! If we wanted to make a "string", we would need to make a length $1$ character `vector`. 

```{r}
# in R
print(mode('a'))
```


## `R` vectors, matrices and arrays versus `numpy` arrays 

This section is for describing the data types that let us store collections of elements that all **share the same type**. Data is very commonly stored in this fashion, so this section is quite important. Once we have one of these objects in a program, we will be interested in learning how to extract different subsets of elements, and how vectorization works.


Recycling
Filtering The extraction of subsets of vectors
Vectorization

## `R` lists versus `Python` lists

When you need to store elements in a container, but you can't guarantee that these elements all have the same type, you need a `list`. Both `R` and `Python` have lists. 



## `R` data frames versus `Pandas` data frames

## `R` factors and tables versus ?

## Classes in `R` and `Python`

## Exercises
