# Object-Oriented Programming

**Object-Oriented Programming (OOP)** is a way of thinking about programs This way of thinking focuses on objects. We already know about objects from the last chapter, so what's new here?

The difference is that we're creating our own types now. In the last chapter we learned about built in types: floating point numbers, lists, arrays, functions, etc. Now we will discuss how you can create your own types in both `R` and `Python`.

This topic should also get its own chapter. There are many differences between OOP in `R` and `Python`--too many to explain in a section of a chapter.

Note that this is just a quick overview that is suitable for us as aspiring data scientists and statisticians. I should should mention that there are plenty of other resources available to you, if you'd like to learn more TODO

## In `Python`

https://docs.python.org/3/tutorial/classes.html

## In `R`

https://adv-r.hadley.nz/oo.html

## General Concepts

- **Polymorphism**
- **Encapsulation**

### Higher-Order  Programming in `R`

All else constant, writing less code is better than writing more code. If you have to change or fix anything, there's less work to do. Here are a few examples in 


#### `*apply` functions in `R`

`lapply`, `sapply`, `apply`

## Reading In Text Files

## Querying a Database
