---
title: "2.2 Lab Assignment"
author: "Taylor Brown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Part

All answers to questions related to R should be written in a file named `data_types_lab.R`. Feel free to work in groups! 
  
1. Answer the same question above, but use R types? Assign your answers to a `character vector` of length four called `questionOne`. 

    + An individual's IP address
    + whether or not an individual attended a study
    + the number of seeds found in a plant
    + the amount of time it takes for a car to race around a track
  
2. Floating points are weird. What gets printed is not the same as what is stored! In R, you can control how many digits get printed by using the `options` function. 

    + Assign `a` to `2/3`
    + `print` `a`, and copy/paste what you see into the variable `aPrint`
    + Take a look at the documentation for `options`. Assign the value of `options()$digits` to `numDigitsStart`
    + Change the number of digits to `22`
    + Again, `print`, `a` and copy/paste what you see into the variable `aPrintv2`
    + Assign the output of `options()$digits` to `numDigitsEnd`
    
3. Floating points are weird. What gets stored might not be what you want. ["The only numbers that can be represented exactly in R’s numeric type are integers and fractions whose denominator is a power of 2."](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f) 

    + Assign the squre root of 2 to `mySqrt`
    + Print the square of this variable
    + Test (using `==`) that this variable is equal to `2`. Assign the result of this test to `isTwoRecoverable`
    + Test for near equality (using `all.equal`) that this variable is "equal" to `2`. Assign the result of this test to `closeEnough`. Make sure to read the documentation for this function because the return type can be tricky!
    
4. Let's flip some coins! Generate a thousand flips of a fair coin. Use `rbinom`, and let heads be coded as `1` and tails coded as `0`. 

    + Assign the thousand raw coin flips to a variable `flips`. Make sure the elements are integers.
    + Create a length `1000` `logical` `vector` called `isHeads`. Whenever you get a heads, make sure the corresponding element is `TRUE` and `FALSE` otherwise.
    + Create a variable called `numHeads` by tallying up the number of heads. 


## Python Part

All answers to questions related to Python should be written in a file named `data_types_lab.py`.


1. Which Python type is ideal for each piece of data? Assign your answers to a `list` of `str`ings called `question_one`. 

    + An individual's IP address
    + whether or not an individual attended a study
    + the number of seeds found in a plant
    + the amount of time it takes for a car to race around a track

2. Floating points are weird. What gets printed is not the same as what is stored! In Python, you need to edit a class's `__str__` method if you want to control how many digits get printed, but we won't do that. Instead, we'll use [`str.format()`](https://docs.python.org/3/library/stdtypes.html#str.format) to return a string directly (instead of copy/paste-ing it).

    + Assign `a` to `2/3`
    + `print` `a`, and copy/paste what you see into the variable `a_print`
    + Create a `str` that displays 22 digits of 2/3. Call it `a_printv2`
    + `print` the above string

3. Floating points are weird. What gets stored might not be what you want. The Python documentation has an excellent discussion of how storage behavior can be surprising. Click [here](https://docs.python.org/3/tutorial/floatingpoint.html) to read it.

    + Assign the squre root of 2 to `my_sqrt`
    + `print` the square of this variable
    + Test (using `==`) that this variable is equal to `2`. Assign the result of this test to `is_two_recoverable`
    + Test for near equality (using `np.close`) that this variable is "equal" to `2`. Assign the result of this test to `close_enough`. 

4. Let's flip some coins (again)! Generate a thousand flips of a fair coin. Use `np.random.binomial`, and let heads be coded as `1` and tails coded as `0`. 

    + Assign the thousand raw coin flips to a variable `flips`. Make sure the elements are integers.
    + Create a length `1000` `list` of `bool`s called `is_heads`. Whenever you get a heads, make sure the corresponding element is `True` and `False` otherwise.
    + Create a variable called `num_heads` by tallying up the number of heads. 



